apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ExampleConstraint
metadata:
  name: example-constraint-instance
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedAnnotation: "example.com/allowed"
